package com.inscripcion3100.api.entity;

public enum StudiesAchieved {
    SIN_ESTUDIOS,
    PRIMARIA_INCOMPLETA,
    PRIMARIA_COMPLETA,
    SECUNDARIO_INCOMPLETO,
    SECUNDARIO_COMPLETO,
    UNIVERSITARIO_INCOMPLETO,
    UNIVERSIRARIO_COMPLETO,
    TERCIARIO_INCOMPLETO,
    TERCIARIO_COMPLETO
}
