spring.application.name=api-inscripcion

#token generado desde linux con: openssl rand -base64 32
api-inscripcion.secret.jwt = UwOq7hNocTrWophg7nnvyvaijRuBNHcZOGbWgdtmEYA=

#tiempo de duracion del tokern
api-inscripcion.jwt.expiration=86400000
